name: Split Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.SUBTREE_PAT }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: core
            split_repository: botovis-core
          - local_path: laravel
            split_repository: botovis-laravel
          - local_path: widget
            split_repository: botovis-widget

    name: Split ${{ matrix.package.local_path }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split and push
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'hikmetozcann'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: 'hikmetozcann'
          user_email: 'hikmetozcann@users.noreply.github.com'

      - name: Split and push with tag
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'hikmetozcann'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: 'hikmetozcann'
          user_email: 'hikmetozcann@users.noreply.github.com'
